# Generated by Django 5.2.6 on 2025-09-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(default='citizen', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('locations', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('evidence', models.ImageField(default='', upload_to='evidence')),
                ('status', models.CharField(default='pending')),
                ('Inspector', models.CharField(default='---')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen')),
            ],
        ),
    ]
