# Generated by Django 5.2.6 on 2025-09-15 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('photo', models.ImageField(default='', upload_to='missing')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen')),
            ],
        ),
    ]
