# Generated by Django 5.2.6 on 2025-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remark',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
